# Generated by Django 5.0.3 on 2024-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statickwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='profile'),
        ),
    ]
