# Generated by Django 5.0.3 on 2024-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(default='slider.jpg', upload_to='slider/'),
        ),
    ]
