# Generated by Django 5.0.3 on 2024-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_slideritem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='slider/slider.jpeg', upload_to='slider/')),
            ],
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(default='slider/slider.jpeg', upload_to='slider/'),
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greating_text', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=50)),
                ('about_item', models.ManyToManyField(to='restaurant.aboutitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
