# Generated by Django 5.0.3 on 2024-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_aboutitem_alter_slideritem_image_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('number_of_people', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('BREAKFAST', 'Breakfast: 8 am to 10 am'), ('LUNCH', 'Lunch: 12 am to 2 pm'), ('DINNER', 'Lunch: 8 pm to 10 pm')], default='BREAKFAST', max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
