# Generated by Django 5.0.3 on 2024-05-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_people', models.IntegerField()),
                ('recipe', models.IntegerField()),
                ('coffee', models.IntegerField()),
                ('best_award', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
